In [2]:
%load_ext autoreload
%autoreload 2
import numpy as np
import sys
sys.path.append('..')
from capacity_management.src.cost_simulation import CostSimulator
from capacity_management.src.optimal_policy_grid_search import grid_search_optimal_caps
from capacity_management.src.greedy_set_capacity import greedy_set_capacity

In [3]:
co = 10
cu = 1
iters=1000
p = 0.15
true_caps = np.array([100]*4)

### Optimal

In [28]:
np.random.seed(0)
grid_search_optimal_caps(co, cu, iters, p, true_caps)

(array([112, 116, 117, 115]), 34.946)

### Chain

In [29]:
np.random.seed(0)
cs = CostSimulator(co, cu, iters, p, true_caps, inf_strategy='chain')
metrics = cs.simulate()
(metrics["raw_inflation"]+true_caps, metrics["total_cost"])

(array([112, 115, 116, 116]), 37.834)

### Independent

In [30]:
np.random.seed(0)
cs = CostSimulator(co, cu, iters, p, true_caps, inf_strategy='independent')
metrics = cs.simulate()
(metrics["raw_inflation"]+true_caps, metrics["total_cost"])

(array([112, 112, 112, 112]), 51.117)

### Greedy

In [4]:
np.random.seed(0)
cs = CostSimulator(co, cu, iters, p, true_caps)
greedy_set_capacity(cs)

(array([114, 117, 114, 103]), 46.578)