In [66]:
%load_ext autoreload
%autoreload 2
import numpy as np
import sys
sys.path.append('..')
from capacity_management.src.mnl_cost_simulation import MNLCostSimulator

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [69]:
mnl = MNLCostSimulator(10, 1, 1, .15, np.array(3*[44]), 'mnl', np.array([15,8,1]))

In [70]:
mnl.mnl_coeff

array([[1.00000000e+00, 9.11050438e-04, 1.66078405e-06],
       [0.00000000e+00, 1.00000000e+00, 9.11881965e-04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

In [105]:
mus = np.arange(11,0,-4)#np.array([100,80,60,40,20])
print(mus)
np.random.seed(0)
mnl = MNLCostSimulator(10, 1, 10, .15, np.array(3*[44]), 'mnl',mus)
mnl.simulate()

[11  7  3]
[0.76506995 0.48714813 0.2982458 ]
[0.67168986 0.35798394 0.03804468]


{'total_cost': 1.4,
 'school_costs': array([0. , 0. , 1.4]),
 'school_overage_costs': array([0., 0., 0.]),
 'school_underage_costs': array([0. , 0. , 1.4]),
 'avg_underfill/movers': 0.4666666666666666,
 'raw_inflation': array([4, 2, 2]),
 'pct_inflation': array([0.09090909, 0.04545455, 0.04545455]),
 'movers': array([ 4. ,  8.2, 12.3]),
 'dropout': None}

In [100]:
mnl = MNLCostSimulator(10, 1, 1, .15, np.array(3*[44]), 'independent', np.array([15,8,1]))
mnl.simulate()

IndexError: index 3 is out of bounds for axis 0 with size 3